### PR TITLE
Visually indicate population activity on map

### PR DESCRIPTION
**Pull request by demyanrogozhin**
Implementation of #8 

Tested:
- visualize activity by color of currency marker
- marker activity animation
- animation on clustering marker
- subscription and live update
- show participants/meetups information in sidebar
- load counters for previews ceremony
 
Change:
Loader is part of UI map. Blockchain connection progress indicated by loading icon in node info box.

### CODE REVIEW

**Comment by brenzi** [comment]
I do like the pulse animation!

In the detail view, when clicking the icon in the atlantic, there is no animation (I see a marker with "4", not "$" in this view.). I only see the animation on global view (with "$" as the marker). Could we have the pulse in detail view as well? Or is that complicated?

also the coloring during assigning and attesting should be yellow in the detail view

Also, I see no animations during attesting phase. There should be a pulse for every extrinsic causing a change in AttestationCount

**Comment by demyanrogozhin** [comment]
In the detail view animation could be done also.
Marker with "4" is a cluster of meetup locations, could be zoomed and it will break into 4 red markers.
It would be easy to add animation and color to cluster icon in details view (same as in currencies view).
Does red pointer meetup markers should be animated? Green circle around red marker wouldn't look harmonic.

Animation happened in attestation phase, at this moment as any other animation only happen in currency marker or cluster of markers.

**Comment by brenzi** [comment]
When I checked, the atlantic currency had a yellow color and a single meetup assigned. it didn't show rhe pulse during attestation. Do you have a fixture to test that? Otgerwise I could stop the community and start. again with 1 meetup at a time when you can test

**Comment by demyanrogozhin** [comment]
I don't have fixtures during testing, cause bot add participants and attestations in phase 1 and 3. Probably bots stop working now, as I don;t

**Comment by brenzi** [comment]
# Acceptance Test
starting with bootstrapping currency 49UkeKNfbLGgZk5h64TrEnirAc27hbdGyDwSPFLg6992 from zero

## REGISTERING
:heavy_check_mark:  currency ($) marker color starts with yellow
:heavy_check_mark:  currency ($) marker color turns green after first registration
:heavy_check_mark:  currency ($) marker shows animation for every registration
:heavy_check_mark:  currency cluster takes best color of children
:heavy_check_mark:  currency cluster shows animation for every registration
:heavy_check_mark: location cluster takes color of currency when zoomed in (if there are still clusters after zooming)
:-1: location cluster shows animation for every registration

I like the total participant counter in the phase widget.

:heavy_check_mark: register one participant for currency HKKAHQhLbLy8b84u1UjnHX9Pqk4FXebzKgtqSt8EKsES. total amount of participants should increase

## ASSIGNING
:heavy_check_mark: currency marker is red if no meetup is assigned
:heavy_check_mark: currency marker is yellow if one meetup is assigned
:question: currency marker is green if 2 meetups are assigned
:heavy_check_mark:  currency cluster takes best color of children

## ATTESTING
:heavy_check_mark: previously assigned color stays
:-1: currency ($) marker shows animation for every attestation
:-1: currency cluster shows animation for every attestation
:-1: location cluster shows animation for every attestation

TODO: will check again when markers are green (>1 meetups assigned)

# TODO
1. animation seem not to work when color is yellow
1. animation seems not to work on location cluster (when there are clusters after zooming in)
1. can we keep the counters in the phase widget even after the phase changes? So that we will still see the total amount of participants registered when the phase is ASSIGNING or ATTESTING? Same for number of meetups assigned

**Comment by demyanrogozhin** [comment]
> TODO
> 1. animation seem not to work when color is yellow

This behavior wasn't tested because marker turns green on every activity that trigger animation.
Only case is when yellow cluster/currency is pulsing is when one meetup was assigned and counter increase in attesting  phase. This wasn't tested on real data, because bootstraping currency has 2 meetups.

> 2. animation seems not to work on location cluster (when there are clusters after zooming in)

Working on it.

> 3. can we keep the counters in the phase widget even after the phase changes?

Yes, it's doable. Counters in past phases wouldn't be visible on mobile view, because it's too narrow and didn't show past phases - that's why it's shows only on current phase.

**Comment by brenzi** [comment]
I just edited the test list. the Problem seems to be the attesting phase, not that one meetup is assigned.
If you need to test from bootstrapping with one meetup, I can restart the bots. Just ping me

**Pull request merged**
