### PR TITLE
Map View for encointer currencies

### PR DESCRIPTION
**Pull request by demyanrogozhin**
Implementation of #2 
@brenzi see comments to this PR for questions if any and implementation details.

### CODE REVIEW

**Comment by brenzi** [comment]
thanks @demyanrogozhin. I tried it with
```
yarn
yarn run start
```
both firefox and chrome show me a map but no locations on the map.

image

**Comment by demyanrogozhin** [comment]
@brenzi I'm not finish yet :)
Currently I trying to figure out how to parse i32F32 in JS. I have no experience with marshaled Rust types in JS and stuck to get correct LatLon that Leafleat accepts.
When I figure it out - switch to currencies markers grouping.

**Comment by brenzi** [comment]
no worries. re fixed point: maybe have a look at

https://github.com/polkadot-js/apps/pull/2324

not sure if it helps

**Comment by demyanrogozhin** [comment]
what do you think about this UI mock?
image

Currently I'm testing responsiveness of design in different resolutions.

**Comment by demyanrogozhin** [comment]
Accidentally close PR, click wrong button.

**Comment by brenzi** [comment]
looks very nice! I think the demurrage rate should be stated per month to be more human readable

**Comment by demyanrogozhin** [comment]
> looks very nice! I think the demurrage rate should be stated per month to be more human readable

In 53438b9 I added finished design of encointer-exploarer.

My idea was: site with map occupied 100% of viewport, with markers on it (when loaded). Also required information boxes visible and has fixed position.
Markers for communities are green with dollar, for meetups - red pointers.

This will looks OK both on desktop and mobile.
App is responsive - if browsed on narrow screen (like phone) sidebar will opens on bottom.
Sandwich button in top-left corner opens navigation menu with links to Encointer resources.

Question:
demurrage looks odd to me. it should be percent value (like in wikipedia articles is skimed why research this topic, I'm new to UBI concepts), instead its huge i128 number returned api (probably hardcoded as well as name_utf8) and multiplied to 438300 (number of blocks in 30 days).
Also demurrage suppose to be negative.

**Comment by demyanrogozhin** [comment]
I documented code as I go in comments, also there is no unit tests.

**Comment by brenzi** [comment]
This looks very nice, thank you!
I've tested it with Firefox, Chrome on desktop as well as Firefox on Android: Works smoothly

I think the details of demurrage go beyond this bounty. I'd be happy to post a follow-up bounty If you'd like to continue

For your reference: Demurrage rate is also a fixpoint value of type `I64F64` It is defined like this:
```
balance_now = balance * exp(-demurrage_rate * number_of_blocks_elapsed)
```

Thanks also for the nice sandwich bar with links!

From my side, this PR is accepted!

**Comment by brenzi** [comment]
Just encountered an issue:

The currency 49UkeKNfbLGgZk5h64TrEnirAc27hbdGyDwSPFLg6992
Lists strange bootstrappers (maybe wrong encoding?)
The currency is defined as follows:
```
{
  "type": "FeatureCollection",
  "currency_meta": {
    "name": "constant population currency",
    "bootstrappers": [
        "5EUXHVefrGT18zqRJJ8vxJTRrmbgA6UUUrAQ3QkmLMLPf7Hd",
        "5Ff3YLGxAtSqpAmorA9srq3zMGFhBuJiQgDvKeXP4ph5yzqp",
        "5CtryXjK4U6VSTyqZEZ44cBUMcwca7uvNKv49CsXcAyaXseQ",
        "5Ci4bxeWR8GAaaWxmksYdcn55tdrRs26waABLVwTYdPxQhkY",
        "5CtadXZuibXHaoNP9VKsoGRc2ih2tHvzdMrDG2GSXFuN89yG",
        "5HK4piM876WwSsBQma1KxVqaAyNX1YVStBNdYwaidtussWyU"
    ]
  },
  "features": [
    {
      "type": "Feature",
      "properties": {},
      "geometry": {
        "type": "Point",
        "coordinates": [
          -36.83544158935547,
          25.171387940538974
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {},
      "geometry": {
        "type": "Point",
        "coordinates": [
          -36.83544158935547,
          25.161387940538974
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {},
      "geometry": {
        "type": "Point",
        "coordinates": [
          -36.83544158935547,
          25.151387940538974
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {},
      "geometry": {
        "type": "Point",
        "coordinates": [
          -36.83544158935547,
          25.141387940538974
        ]
      }
    }
  ]
}
```
The MapView lists bootatrappers as
```
8BGAoUQTJD9r9LEsZma5kaCGywkntaDTKTpQQYeM7nrM
BhGDW9aGrurPuJGW1pGyZbWtPtQLnYEskyzzci7pBQuv
3UNbZwX8Wx2ArnnKmmyiAKDPw6HcujxzFroetFWaX6jn
2vDnA7yao9DvFP1Jbwd4SjqwTbrFdMTQbZP8A9pEnrix
3TXwCawuYBAxeFWX9ixovH6Tu8FGtHhEyoXA3wwD6aey
Gd8w4EJbVXarMSpqXKSJRRq1PrLiuRvZAyXrZsjdLM3B
```
It seems they are not `ss58` encoded. polkadot-js should take care of this actually....

**Comment by demyanrogozhin** [comment]
> It seems they are not `ss58` encoded. polkadot-js should take care of this actually....
Indeed, it was string that polkadot returns, and I was doing base58 encode on, doh! fixed in  8fdb1b3

**Pull request merged**
