### PR TITLE
fixed the tentative community Growth function

### LINKED ISSUE #101: tentative community growth does not make sense
with 42 registered participants and 8 newbies, tentative growth is reported as 0.04%

given 184 reputables, 8 newbies should be 5%

image

### PR DESCRIPTION
**Pull request by Jay-Forrer**
closes #101

### CODE REVIEW

**Comment by brenzi** [comment]
please always mention the issue a PR is closing. Did it for this one

Something is still odd. Your formula looks alright for me, but when I tested with Leu community, the numbers don't match:
image

(12 newbies+16 endorsees)/201 reputables = 13.9%, not 6%

**Comment by brenzi** [comment]
and I just realized that we probably need to only count newbies that have been assigned (if assignments have been done). As you already feature "newbies unassigned", this should be easy to do?

**Comment by Jay-Forrer** [comment]
Found the problem that we had with the tentative growth function. when we do newbies + endorsees we actually concatenate the two numbers together (why? newbies and endorsees have the type 'any' which might explain the problem). And only using the assigned Newbies shouldn't be a problem.

**Comment by brenzi** [comment]
I have to believe you didn't test this. Your code now displays 0.11% tentative community growth which probably should be 11%?

image

**Comment by Jay-Forrer** [comment]
yes, honest mistake. Forgot that we wanted it in Percent. Now it should be correct

**Review by brenzi — APPROVED** [review]
now it does what it should (I only tested during ATTESTING phase)

also here, please do not add yarn stuff. had to clean it up: please check my latest commit

**Pull request merged**
