### PR TITLE
show number of submitted attesters

### LINKED ISSUE #102: show number of submitted attesters
During attesting phase, it would be interesting to see, how many attendees have already submitted their attestations. In the phase bar it is already reporeted as a global total, but it would be nice to see this in the community info panel, below "Assigned Participants for this ceremony"

### PR DESCRIPTION
**Pull request by Jay-Forrer**
closes #102

### CODE REVIEW

**Review by brenzi — CHANGES_REQUESTED** [review]
does not work
image

in this screenshot, 41 attersters have submitted (only leu community) as shown in the top bar. 
the currency view should say:

"Number of attestation submissions: 41"

It won't hurt to still show the assignment stats with all the reputation types

**Comment by Jay-Forrer** [comment]
I found out that It only showed it in the currency info in the registering phase. Changed that and let's hope this was the problem

**Comment by Jay-Forrer** [comment]
Furthermore. My function should show the number of participants locally, while the Attesting box shows the number globally, so I don't think I need to implement a aggregate the local participant number to a global scale.

**Comment by brenzi** [comment]
This PR now does what it should, thanks you.

But: You seem to have committed the yarn cache. never do that. never just add everything. Only your code changes. Please clean up! Check the "Files Changed" in this PR. should only be those you edited manually

**Review by brenzi — APPROVED** [review]
cleaned up the added files

**Pull request merged**
