### PR TITLE
trying to implement community business task

### LINKED ISSUE #69: show community businesses on map (option)
* add widget to select to see businesses or not 
* optionally: this could also be used to display all meetup locations of a community

extension:
would be nice to integrate the explorer in bazaar-web as an iframe, showing businesses

### PR DESCRIPTION
**Pull request by Jay-Forrer**
closes #69

### CODE REVIEW

**Comment by Jay-Forrer** [comment]
I used npm install @material-ui/core --legacy-peer-deps. Don't know if I should have done that

**Comment by Jay-Forrer** [comment]
yea. will look into that how i can solve this problem.

**Comment by Jay-Forrer** [comment]
I might need to push the formControlLable Module, to solve this issue

**Comment by Jay-Forrer** [comment]
seems like I still have the issue of not being able to push material-ui/core to github...

**Comment by brenzi** [comment]
issue #69 is not scheduled to be worked on yet. this has to wait. closing PR for now

**Pull request closed without merging**
