### PR TITLE
update encointer_js to 0.7.1

### PR DESCRIPTION
**Pull request by anizeani**

### CODE REVIEW

**Comment by anizeani** [comment]
I might need to add a python installation to yml file?

Screenshot from 2022-02-20 22-43-24

**Comment by clangenb** [comment]
The yarn install seems to fail at installing an optional dependency.

I don't know the reason for this problem, but as we can successfully compile the explorer, I guess the problem does not do any harm.

**Comment by clangenb** [comment]
I close this in favor of #71, where @encointer is updated to v0.7.2

**Comment by anizeani** [comment]
the reason for the error is written: python 2.7.18 is found but python >= 3.6 is required. but i agree that the optional dependency is questionable, maybe its not even needed and should be removed..

**Pull request closed without merging**
